#!/bin/bash

# config
source $0.conf

[ -z "$DIRNAME" ] && (echo "Missing DIRNAME" && exit 1)
[ -z "$DB_USER" ] && (echo "Missing DB_USER" && exit 1)

# helpers
CURDATE=$(date +"%Y-%m-%d")

report_error ()
{
    echo "[ERROR]"
}

backup_size()
{
    echo -n "[disk usage: "
    # os x/freebsd:
    echo -n `du -h -d 1 $1 | cut -f 1`
    echo "]"
    # linux:
    # du -h --max-depth=0 $DIRNAME/
}

# arguments: partial_path db1 db2 db3 .. dbN
# e.g. db_backup weekly db1
db_backup ()
{
    # DIRNAME/weekly
    DIR=$DIRNAME/$1
    mkdir -p $DIR
    # echo "${*:2}"
    for ARG in "${@:2}" # "$@"
    do
        # perform the backup
        FILENAME=${ARG}-${CURDATE}.sql.gz
        FULLPATH=${DIR}/${FILENAME}
        echo -n "* backing up ${ARG} to ${FILENAME}"
        if [ -z "$DB_PASS" ]; then
            mysqldump -u ${DB_USER} ${ARG} --single-transaction --quick|gzip -5 > ${FULLPATH} || (report_error && rm ${FULLPATH})
        else
            mysqldump -u ${DB_USER} -p${DB_PASS}  ${ARG} --single-transaction --quick|gzip -5 > ${FULLPATH} || (f_error && rm ${FULLPATH})
        fi
        echo -n " "

        # report backup size
        backup_size $DIR
    done
}

# TODO zjistit z sql serveru seznam databazi...
# a vyhodit z toho seznamu db ktery nepotrebuju...

case $1 in
    daily)
        echo "* performing $1 backups"
        db_backup daily ${BACKUP_DAILY[*]}
        ;;
    weekly)
        echo "* performing $1 backups"
        db_backup weekly ${BACKUP_WEEKLY[*]}
        ;;
    monthly)
        echo "* performing $1 backups"
        db_backup monthly ${BACKUP_MONTHLY[*]}
        ;;
    cleanup)
        echo "* removing old backups"
        find $DIRNAME/daily -mtime +${DELETE_DAILY_AFTER} -exec ls {} \; -exec rm {} \;
        find $DIRNAME/weekly -mtime +${DELETE_WEEKLY_AFTER} -exec ls {} \; -exec rm {} \;
        find $DIRNAME/monthly -mtime +${DELETE_MONTHLY_AFTER} -exec ls {} \; -exec rm {} \;
        ;;
    *)
        echo "Usage: $0 <daily|weekly|monthly>"
        echo "Performs backups of databases configured for given time period."
        exit 1
        ;;
esac
